
DROP TABLE F_WEB_IM_GROUP_MEMBER;

CREATE TABLE F_WEB_IM_GROUP
(
   GROUP_ID             VARCHAR2(32) NOT NULL,
   OS_ID                VARCHAR2(20) NOT NULL,
   GROUP_TYPE           CHAR NOT NULL,
   GROUP_NAME           VARCHAR2(100) NOT NULL ,
   CREATOR              VARCHAR2(32) NOT NULL,
   CREATE_TIME          DATE ,
   GROUP_NOTICE         VARCHAR2(1000),
   PRIMARY KEY (GROUP_ID)
);

CREATE TABLE F_WEB_IM_GROUP_MEMBER
(
   OS_ID                VARCHAR2(20) NOT NULL,
   USER_CODE            VARCHAR2(32) NOT NULL,
   GROUP_ID             VARCHAR2(32) NOT NULL,
   GROUP_MEMO           VARCHAR2(1000) ,
   GROUP_ALIAS          VARCHAR2(100),
   JOIN_TIME            DATE NOT NULL,
   LAST_PUST_TIME       DATE NOT NULL,
   PRIMARY KEY (USER_CODE, UNIT_CODE)
);

