apiVersion: v1
kind: Service
metadata:
  name: im
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 10085
  selector:
    app: im
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: im
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: im
  template:
    metadata:
      labels:
        app: im
    spec:
      containers:
      - name: im
        image: hub.centit.com/ctm/im:<BUILD_TAG>
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-secret
